<div id="oklala" style="display: none;border-radius:3px;border:1px solid #3883CC;"><center>
<a href="javascript:tag(':)',' ')"><img src="/images/smileys/user/emoz/1.gif"/></a> 

<a href="javascript:tag(':~',' ')"><img src="/images/smileys/user/emoz/2.gif"/></a>
<a href="javascript:tag(':B',' ')"><img src="/images/smileys/user/emoz/3.gif"/></a>
<a href="javascript:tag(':|',' ')"><img src="/images/smileys/user/emoz/4.gif"/></a>
<a href="javascript:tag('8-)',' ')"><img src="/images/smileys/user/emoz/5.gif"/></a>
<a href="javascript:tag(':-((',' ')"><img src="/images/smileys/user/emoz/6.gif"/></a>
<a href="javascript:tag(':$',' ')"><img src="/images/smileys/user/emoz/7.gif"/></a>
<a href="javascript:tag(':X',' ')"><img src="/images/smileys/user/emoz/8.gif"/></a>
<a href="javascript:tag(':Z',' ')"><img src="/images/smileys/user/emoz/9.gif"/></a>
<a href="javascript:tag(':((',' ')"><img src="/images/smileys/user/emoz/10.gif"/></a>
<a href="javascript:tag(':-|',' ')"><img src="/images/smileys/user/emoz/11.gif"/></a>
<a href="javascript:tag(':-H',' ')"><img src="/images/smileys/user/emoz/12.gif"/></a>
<a href="javascript:tag(':P',' ')"><img src="/images/smileys/user/emoz/13.gif"/></a>
<a href="javascript:tag(':D',' ')"><img src="/images/smileys/user/emoz/14.gif"/></a>
<a href="javascript:tag(':o',' ')"><img src="/images/smileys/user/emoz/15.gif"/></a>
<a href="javascript:tag(':(',' ')"><img src="/images/smileys/user/emoz/16.gif"/></a>
<a href="javascript:tag(':+',' ')"><img src="/images/smileys/user/emoz/17.gif"/></a>
<a href="javascript:tag('--B',' ')"><img src="/images/smileys/user/emoz/18.gif"/></a>
<a href="javascript:tag(':Q',' ')"><img src="/images/smileys/user/emoz/19.gif"/></a>
<a href="javascript:tag(':T',' ')"><img src="/images/smileys/user/emoz/20.gif"/></a>
<a href="javascript:tag(';P',' ')"><img src="/images/smileys/user/emoz/21.gif"/></a>
<a href="javascript:tag(';-D',' ')"><img src="/images/smileys/user/emoz/22.gif"/></a>
<a href="javascript:tag(';D',' ')"><img src="/images/smileys/user/emoz/23.gif"/></a>
<a href="javascript:tag(';O',' ')"><img src="/images/smileys/user/emoz/24.gif"/></a>
<a href="javascript:tag(';G',' ')"><img src="/images/smileys/user/emoz/25.gif"/></a>
<a href="javascript:tag('|-)',' ')"><img src="/images/smileys/user/emoz/26.gif"/></a>
<a href="javascript:tag(':!',' ')"><img src="/images/smileys/user/emoz/27.gif"/></a>
<a href="javascript:tag(':L',' ')"><img src="/images/smileys/user/emoz/28.gif"/></a>
<a href="javascript:tag(':kl',' ')"><img src="/images/smileys/user/emoz/29.gif"/></a>
<a href="javascript:tag(':;',' ')"><img src="/images/smileys/user/emoz/30.gif"/></a>
<a href="javascript:tag(';F',' ')"><img src="/images/smileys/user/emoz/31.gif"/></a>
<a href="javascript:tag(';-S',' ')"><img src="/images/smileys/user/emoz/32.gif"/></a>
<a href="javascript:tag(';?',' ')"><img src="/images/smileys/user/emoz/33.gif"/></a>
<a href="javascript:tag(';-X',' ')"><img src="/images/smileys/user/emoz/34.gif"/></a>
<a href="javascript:tag(':-F',' ')"><img src="/images/smileys/user/emoz/35.gif"/></a>
<a href="javascript:tag(';8',' ')"><img src="/images/smileys/user/emoz/36.gif"/></a>
<a href="javascript:tag(';!',' ')"><img src="/images/smileys/user/emoz/37.gif"/></a>
<a href="javascript:tag(';-!',' ')"><img src="/images/smileys/user/emoz/38.gif"/></a>
<a href="javascript:tag(';XX',' ')"><img src="/images/smileys/user/emoz/39.gif"/></a>
<a href="javascript:tag(':-BYE',' ')"><img src="/images/smileys/user/emoz/40.gif"/></a>
<a href="javascript:tag(':WIPE',' ')"><img src="/images/smileys/user/emoz/41.gif"/></a>
<a href="javascript:tag(':-DIG',' ')"><img src="/images/smileys/user/emoz/42.gif"/></a>
<a href="javascript:tag(':handclap',' ')"><img src="/images/smileys/user/emoz/43.gif"/></a>
<a href="javascript:tag('/-huan',' ')"><img src="/images/smileys/user/emoz/44.gif"/></a>
<a href="javascript:tag('B-)',' ')"><img src="/images/smileys/user/emoz/45.gif"/></a>
<a href="javascript:tag(':-L',' ')"><img src="/images/smileys/user/emoz/46.gif"/></a>
<a href="javascript:tag(':-R',' ')"><img src="/images/smileys/user/emoz/47.gif"/></a>
<a href="javascript:tag(':-O',' ')"><img src="/images/smileys/user/emoz/48.gif"/></a>
<a href="javascript:tag('/+huan',' ')"><img src="/images/smileys/user/emoz/49.gif"/></a>
<a href="javascript:tag('P-(',' ')"><img src="/images/smileys/user/emoz/50.gif"/></a>
<a href="javascript:tag(':--|',' ')"><img src="/images/smileys/user/emoz/51.gif"/></a>
<a href="javascript:tag('X-)',' ')"><img src="/images/smileys/user/emoz/52.gif"/></a>
<a href="javascript:tag(':*',' ')"><img src="/images/smileys/user/emoz/53.gif"/></a>
<a href="javascript:tag(';-A',' ')"><img src="/images/smileys/user/emoz/54.gif"/></a>
<a href="javascript:tag('8*',' ')"><img src="/images/smileys/user/emoz/55.gif"/></a>
<a href="javascript:tag('/-showlove',' ')"><img src="/images/smileys/user/emoz/56.gif"/></a>
<a href="javascript:tag('/-rose',' ')"><img src="/images/smileys/user/emoz/57.gif"/></a>
<a href="javascript:tag('/-fade',' ')"><img src="/images/smileys/user/emoz/58.gif"/></a>
<a href="javascript:tag('/-heart',' ')"><img src="/images/smileys/user/emoz/59.gif"/></a>
<a href="javascript:tag('/-break',' ')"><img src="/images/smileys/user/emoz/60.gif"/></a>
<a href="javascript:tag('/-coffee',' ')"><img src="/images/smileys/user/emoz/61.gif"/></a>
<a href="javascript:tag('/-cake',' ')"><img src="/images/smileys/user/emoz/62.gif"/></a>
<a href="javascript:tag('/-li',' ')"><img src="/images/smileys/user/emoz/63.gif"/></a>
<a href="javascript:tag('/-bome',' ')"><img src="/images/smileys/user/emoz/64.gif"/></a>
<a href="javascript:tag('/-bd',' ')"><img src="/images/smileys/user/emoz/65.gif"/></a>
<a href="javascript:tag('/-shit',' ')"><img src="/images/smileys/user/emoz/66.gif"/></a>
<a href="javascript:tag('/-strong',' ')"><img src="/images/smileys/user/emoz/67.gif"/></a>
<a href="javascript:tag('/-weak',' ')"><img src="/images/smileys/user/emoz/68.gif"/></a>
<a href="javascript:tag('/-share',' ')"><img src="/images/smileys/user/emoz/69.gif"/></a>
<a href="javascript:tag('/-v',' ')"><img src="/images/smileys/user/emoz/70.gif"/></a>
<a href="javascript:tag('/-thanks',' ')"><img src="/images/smileys/user/emoz/71.gif"/></a>
<a href="javascript:tag('/-jj',' ')"><img src="/images/smileys/user/emoz/72.gif"/></a>
<a href="javascript:tag('/-punch',' ')"><img src="/images/smileys/user/emoz/73.gif"/></a>
<a href="javascript:tag('/-bad',' ')"><img src="/images/smileys/user/emoz/74.gif"/></a>
<a href="javascript:tag('/-loveu',' ')"><img src="/images/smileys/user/emoz/75.gif"/></a>
<a href="javascript:tag('/-no',' ')"><img src="/images/smileys/user/emoz/76.gif"/></a>
<a href="javascript:tag('/-ok',' ')"><img src="/images/smileys/user/emoz/77.gif"/></a>
<a href="javascript:tag('/-flag',' ')"><img src="/images/smileys/user/emoz/78.gif"/></a>

</center>
</div>
<div id="fucke" style="display: none;border-radius:3px;border:1px solid #3883CC;"><center>
<a href="javascript:tag('/dui1',' ')"><img src="/images/smileys/user/emoz/dui1.png"/>
<a href="javascript:tag('/dui2',' ')"><img src="/images/smileys/user/emoz/dui2.png"/>
<a href="javascript:tag('/dui3',' ')"><img src="/images/smileys/user/emoz/dui3.png"/>
<a href="javascript:tag('/dui4',' ')"><img src="/images/smileys/user/emoz/dui4.png"/>
<a href="javascript:tag('/dui5',' ')"><img src="/images/smileys/user/emoz/dui5.png"/>
<a href="javascript:tag('/dui6',' ')"><img src="/images/smileys/user/emoz/dui6.png"/>
<a href="javascript:tag('/dui7',' ')"><img src="/images/smileys/user/emoz/dui7.png"/>
<a href="javascript:tag('/dui8',' ')"><img src="/images/smileys/user/emoz/dui8.png"/>
<a href="javascript:tag('/dui9',' ')"><img src="/images/smileys/user/emoz/dui9.png"/>
<a href="javascript:tag('/duia',' ')"><img src="/images/smileys/user/emoz/dui10.png"/>
<a href="javascript:tag('/duib',' ')"><img src="/images/smileys/user/emoz/dui11.png"/>
<a href="javascript:tag('/duic',' ')"><img src="/images/smileys/user/emoz/dui12.png"/>
<a href="javascript:tag('/duid',' ')"><img src="/images/smileys/user/emoz/dui13.png"/>
<a href="javascript:tag('/duie',' ')"><img src="/images/smileys/user/emoz/dui14.png"/>
<a href="javascript:tag('/duif',' ')"><img src="/images/smileys/user/emoz/dui15.png"/>
</a>
</center>
</div>
<div id="sticks" style="display: none;border-radius:3px;border:1px solid #3883CC;"><center>
<a href="javascript:tag('/likemanht',' ')"><img src="/images/smileys/user/emoz/thinh1.png"/>
<a href="javascript:tag('/byet',' ')"><img src="/images/smileys/user/emoz/thinh2.png"/>
<a href="javascript:tag('/bant',' ')"><img src="/images/smileys/user/emoz/thinh3.png"/>
<a href="javascript:tag('/hit',' ')"><img src="/images/smileys/user/emoz/thinh4.png"/>
<a href="javascript:tag('/cot',' ')"><img src="/images/smileys/user/emoz/thinh5.png"/>
<a href="javascript:tag('/khongt',' ')"><img src="/images/smileys/user/emoz/thinh6.png"/>
<a href="javascript:tag(':-1:',' ')"><img src="/images/smileys/user/Sitcker/1.gif"/>
<a href="javascript:tag(':-2:',' ')"><img src="/images/smileys/user/Sitcker/2.gif"/>
<a href="javascript:tag(':-3:',' ')"><img src="/images/smileys/user/Sitcker/3.gif"/>
<a href="javascript:tag(':-4:',' ')"><img src="/images/smileys/user/Sitcker/4.gif"/>
<a href="javascript:tag(':-5:',' ')"><img src="/images/smileys/user/Sitcker/5.gif"/>
<a href="javascript:tag(':-6:',' ')"><img src="/images/smileys/user/Sitcker/6.gif"/>
<a href="javascript:tag(':-7:',' ')"><img src="/images/smileys/user/Sitcker/7.gif"/>
<a href="javascript:tag(':-8:',' ')"><img src="/images/smileys/user/Sitcker/8.gif"/>
<a href="javascript:tag(':-9:',' ')"><img src="/images/smileys/user/Sitcker/9.gif"/>
<a href="javascript:tag(':-10:',' ')"><img src="/images/smileys/user/Sitcker/10.gif"/>
<a href="javascript:tag(':-11:',' ')"><img src="/images/smileys/user/Sitcker/11.gif"/>
<a href="javascript:tag(':-12:',' ')"><img src="/images/smileys/user/Sitcker/12.gif"/>
<a href="javascript:tag(':-13:',' ')"><img src="/images/smileys/user/Sitcker/13.gif"/>
<a href="javascript:tag(':-14:',' ')"><img src="/images/smileys/user/Sitcker/14.gif"/>
<a href="javascript:tag(':-15:',' ')"><img src="/images/smileys/user/Sitcker/15.gif"/>
<a href="javascript:tag(':-16:',' ')"><img src="/images/smileys/user/Sitcker/16.gif"/>
<a href="javascript:tag(':-17:',' ')"><img src="/images/smileys/user/Sitcker/17.gif"/>
<a href="javascript:tag(':-18:',' ')"><img src="/images/smileys/user/Sitcker/18.gif"/>
<a href="javascript:tag(':-19:',' ')"><img src="/images/smileys/user/Sitcker/19.gif"/>
<a href="javascript:tag(':-20:',' ')"><img src="/images/smileys/user/Sitcker/20.gif"/>
<a href="javascript:tag(':-21:',' ')"><img src="/images/smileys/user/Sitcker/21.gif"/>
<a href="javascript:tag(':-22:',' ')"><img src="/images/smileys/user/Sitcker/22.gif"/>
<a href="javascript:tag(':-23:',' ')"><img src="/images/smileys/user/Sitcker/23.gif"/>
<a href="javascript:tag(':-24:',' ')"><img src="/images/smileys/user/Sitcker/24.gif"/>
<a href="javascript:tag(':-25:',' ')"><img src="/images/smileys/user/Sitcker/25.gif"/>
<a href="javascript:tag(':-26:',' ')"><img src="/images/smileys/user/Sitcker/26.gif"/>
<a href="javascript:tag(':-27:',' ')"><img src="/images/smileys/user/Sitcker/27.gif"/>
<a href="javascript:tag(':-28:',' ')"><img src="/images/smileys/user/Sitcker/28.gif"/>
<a href="javascript:tag(':-29:',' ')"><img src="/images/smileys/user/Sitcker/29.gif"/>
<a href="javascript:tag(':-30:',' ')"><img src="/images/smileys/user/Sitcker/30.gif"/>
<a href="javascript:tag(':-31:',' ')"><img src="/images/smileys/user/Sitcker/31.gif"/>
<a href="javascript:tag(':-32:',' ')"><img src="/images/smileys/user/Sitcker/32.gif"/>
<a href="javascript:tag(':-33:',' ')"><img src="/images/smileys/user/Sitcker/33.gif"/>
<a href="javascript:tag(':-34:',' ')"><img src="/images/smileys/user/Sitcker/34.gif"/>
<a href="javascript:tag(':-35:',' ')"><img src="/images/smileys/user/Sitcker/35.gif"/>
<a href="javascript:tag(':-36:',' ')"><img src="/images/smileys/user/Sitcker/36.gif"/>
<a href="javascript:tag(':-37:',' ')"><img src="/images/smileys/user/Sitcker/37.gif"/>
<a href="javascript:tag(':-38:',' ')"><img src="/images/smileys/user/Sitcker/38.gif"/>
<a href="javascript:tag(':-39:',' ')"><img src="/images/smileys/user/Sitcker/39.gif"/>
<a href="javascript:tag(':-40:',' ')"><img src="/images/smileys/user/Sitcker/40.gif"/>
<a href="javascript:tag(':-41:',' ')"><img src="/images/smileys/user/Sitcker/41.gif"/>
<a href="javascript:tag(':-42:',' ')"><img src="/images/smileys/user/Sitcker/42.gif"/>
<a href="javascript:tag(':-43:',' ')"><img src="/images/smileys/user/Sitcker/43.gif"/>
<a href="javascript:tag(':-44:',' ')"><img src="/images/smileys/user/Sitcker/44.gif"/>
</a>
</center>
</div>